name: Mula

on:
  push:
    branches: [ master ]
jobs:
  laravel-deployer:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.MULA_HOST }}
          username: ${{ secrets.MULA_USER }}
          password: ${{ secrets.MULA_PASS }}
          script: 'RUN_YPUR_DEPLOYMENT_SCRIPT' #cd /var/www/html/MerqataAPI && ./server_deploy.sh
